### ISSUE TITLE
Merge PRs

### ISSUE THREAD

**Issue by bnjmnt4n** [tlrobinson/evil.css#20]
There are plenty of rather good and interesting PRs here, however development of evil.css has pretty much dried up. Do you need help maintaining evil.css?

**Comment by simonaronsson** [comment]
I think this question is legit. I dont know tbh if my change is in the spirit of the project, however it would be nice to atleast receive an accept or decline instead of getting placed in the PR Pending-Limbo.

**Comment by bnjmnt4n** [comment]
ping @tlrobinson

**Comment by tlrobinson** [comment]
Sorry, this project isn't exactly my top priority.

I pulled some of PRs but now some of them don't merge cleanly. If you could merge your changes with master I'll pull it.

**Comment by bnjmnt4n** [comment]
Thanks @tlrobinson!
Pinging @maximilienwolfgang @adjohu @modermodem @tomlane
Please rebase your PRs on top of master.

**Comment by battaglr** [comment]
@tlrobinson if you need help, I'll be glad to maintain this evil project.
